version: "3"

tasks:
  default:
    - echo "first use task install"
    - echo "Then you can use dev format deploy"

  dev:
    deps: [dev:sass, dev:serve]

  dev:serve:
    cmds:
      - pnpm eleventy --serve
    daemon: true
    silent: false

  dev:sass:
    cmds:
      - pnpm sass --watch _includes/src/scss:public/assets --no-source-map --watch _includes/src/partials:public/assets
    daemon: true
    silent: false

  build:clean:
    cmds:
      - rm -rf public

  build:sass:
    cmds:
      - pnpm sass _includes/src/scss:public/assets --no-source-map

  build:assets:
    cmds:
      - cp -r assets public/

  build:lint:
    sources:
      - public/assets/main.css
    cmds:
      - pnpm stylelint public/assets/main.css --fix

  build:
    sources:
      - _includes/**/*.njk
      - index.njk
      - _includes/src/**/*.{scss,njk}

    cmds:
      - task: build:clean
      - pnpm eleventy
      - task: build:sass
      - task: build:assets
      - task: lint
      - task: build:lint
      - task: format

  deploy:
    deps: [format]
    cmds:
      - git subtree push --prefix public origin deploy

  format:
    sources:
      - _includes/**/*.njk
      - index.njk
      - _includes/src/**/*.{scss,njk}
    cmds:
      - prettier ./ --write

  lint:
    sources:
      - _includes/src/scss/**/*.scss
      - _includes/src/partials/**/*.scss

    cmds:
      - pnpm stylelint _includes/src/scss/**/*.scss --fix
      - pnpm stylelint _includes/src/scss/*.scss --fix
      - pnpm stylelint _includes/src/partials/**/*.scss --fix

  setup:
    run: once
    cmds:
      - echo "Installing deps for project, volta, node, pnpm, prettier"
      - |
        if [[ "$OS" == "windows" ]]; then
          winget install Volta.Volta
        else
          curl https://get.volta.sh | bash
        fi
      - volta install node
      - volta install pnpm
      - volta install prettier

  install:
    deps: [setup]
    source: package.json
    cmds:
      - echo "Installing package.json deps"
      - pnpm install
