version: '3'

tasks:
  build:
    sources:
      - index.pug
      - includes/*.pug
      - assets/scss/*.scss
    cmds:
      - rm -rf public
      - mv .git .git.bk #Plugins doesn't work if a have a .git in a subdir
      - yarn parcel build {{.TASKFILE_DIR}}/*.pug --dist-dir {{.TASKFILE_DIR}}/public --no-source-maps --no-cache --public-url .
      - mv .git.bk .git #I'm investigating why
      - task: format
        vars: { SUB_DIR: public/ }

  dev:
    cmds:
      - yarn parcel {{.TASKFILE_DIR}}/index.pug --dist-dir {{.TASKFILE_DIR}}/dist --no-source-maps

  deploy:
    deps: [build]
    cmds:
      - git subtree push --prefix public origin deploy

  setup_deploy:
    cmds:
      - git push origin deploy:deploy

  format:
    sources:
      - public/*.html
      - public/*.css
    cmds:
      - prettier {{.ROOT_DIR}}/{{.SUB_DIR}} --write --config ../../.prettierrc
